[package]
name = "hdr10plus_tool"
version = "1.3.1"
authors = ["quietvoid"]
edition = "2021"
rust-version = "1.57.0"
license = "MIT"

[dependencies]
bitvec_helpers = "1.0.2"
hdr10plus = { path = "./hdr10plus", features = ["hevc", "json"] }
hevc_parser = { version = "0.4.7", features = ["hevc_io"] }
clap = { version = "3.2.17", features = ["derive", "wrap_help", "deprecated"] }
serde_json = { version = "1.0.85", features = ["preserve_order"] }
indicatif = "0.17.0"
bitvec = "1.0.1"
anyhow = "1.0.62"
thiserror = "1.0.32"

[dev-dependencies]
assert_cmd = "2.0.4"
assert_fs = "1.0.7"
predicates = "2.1.1"

[[bin]]
name = "hdr10plus_tool"
path = "src/main.rs"

[patch.crates-io]
hevc_parser = { path = "vendor/hevc_parser" }
